@startuml
class Disk {
}

class Cluster {
}

class Folder {
}

class File {
}

class Data {
}

'Диск состоит из пронумерованных кластеров
Disk "1" *-- "1.." Cluster

'На диске есть именованные папки
Disk "1" o-- "0.." Folder

'именованные папки, в которые вложены папки
Folder o-- Folder 

'Или именованные файлы
Folder -- File

'
File *-- Data


Folder o-- Cluster
File o-- Cluster
@enduml
