@startuml

class ReliabilityQualityFactor {
    - name: "Надежность"
    - criteria: List<ReliabilityCriterion>
}

class ReliabilityCriterion {
    - name: String
    - description: String
    - metrics: List<ReliabilityMetric>
}

class ReliabilityMetric {
    - name: String
    - value: double
    - unit: String
}

ReliabilityQualityFactor "1" -- "0..*" ReliabilityCriterion : includes
ReliabilityCriterion "1" -- "0..*" ReliabilityMetric : measures

@enduml

